"""Application-facing persistence ports."""

from typing import Protocol, TypedDict

from wnacg.domain.models import DownloadTask, TaskStatus


class ImageRecord(TypedDict):
    """Persistence-neutral image progress record."""

    task_id: str
    image_index: int
    view_url: str
    raw_url: str
    status: str


class TaskRepository(Protocol):
    """Operations required by the download use cases."""

    def save_task(self, task: DownloadTask) -> None: ...
    def get_all_tasks(self) -> list[DownloadTask]: ...
    def get_task(self, task_id: str) -> DownloadTask | None: ...
    def get_task_by_aid(self, aid: str) -> DownloadTask | None: ...
    def update_task_status(
        self,
        task_id: str,
        status: TaskStatus,
        error_message: str | None = None,
    ) -> None: ...
    def update_task_progress(self, task_id: str, progress: float, downloaded: int, total: int) -> None: ...
    def delete_task(self, task_id: str) -> None: ...
    def reset_downloading_tasks(self) -> None: ...
    def save_view_links(self, task_id: str, view_links: list[str]) -> None: ...
    def save_raw_links(self, task_id: str, raw_urls: list[str]) -> None: ...
    def get_images(self, task_id: str) -> list[ImageRecord]: ...
    def update_image_raw_url(self, task_id: str, image_index: int, raw_url: str) -> None: ...
    def update_image_status(self, task_id: str, image_index: int, status: str) -> None: ...
